version: '3.1'

networks:
  gbn:

services:
 
 beaconega:
    build:
      context: .
    container_name: apiplatz
    ports:
      - "5700:5700"
    entrypoint: ['python','server.py']
    networks:
      - gbn

 client:
    build:
      context: ./client
    command: [ "yarn", "start" ]
    container_name: perusable-client
    depends_on:
      - beaconega
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
    networks:
      - gbn